dev/307/rails/rainbow-sparkle/config/routes.rb
Rails.application.routes.draw do
  resources :flavors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

dev/307/rails/rainbow-sparkle/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

dev/307/rails/rainbow-sparkle/app/models/flavor.rb
class Flavor < ApplicationRecord
end

dev/307/rails/rainbow-sparkle/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

dev/307/rails/rainbow-sparkle/app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController
  before_action :set_flavor, only: [:show, :edit, :update, :destroy]

  # GET /flavors
  # GET /flavors.json
  def index
    @flavors = Flavor.all
  end

  # GET /flavors/1
  # GET /flavors/1.json
  def show
  end

  # GET /flavors/new
  def new
    @flavor = Flavor.new
  end

  # GET /flavors/1/edit
  def edit
  end

  # POST /flavors
  # POST /flavors.json
  def create
    @flavor = Flavor.new(flavor_params)

    respond_to do |format|
      if @flavor.save
        format.html { redirect_to @flavor, notice: 'Flavor was successfully created.' }
        format.json { render :show, status: :created, location: @flavor }
      else
        format.html { render :new }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flavors/1
  # PATCH/PUT /flavors/1.json
  def update
    respond_to do |format|
      if @flavor.update(flavor_params)
        format.html { redirect_to @flavor, notice: 'Flavor was successfully updated.' }
        format.json { render :show, status: :ok, location: @flavor }
      else
        format.html { render :edit }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flavors/1
  # DELETE /flavors/1.json
  def destroy
    @flavor.destroy
    respond_to do |format|
      format.html { redirect_to flavors_url, notice: 'Flavor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flavor
      @flavor = Flavor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flavor_params
      params.require(:flavor).permit(:name, :color)
    end
end

dev/307/rails/rainbow-sparkle/app/helpers/application_helper.rb
module ApplicationHelper
end

dev/307/rails/rainbow-sparkle/app/helpers/flavors_helper.rb
module FlavorsHelper
end

dev/307/rails/rainbow-sparkle/app/views/flavors/_form.html.erb
<%= form_for(flavor) do |f| %>
  <% if flavor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flavor.errors.count, "error") %> prohibited this flavor from being saved:</h2>

      <ul>
      <% flavor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dev/307/rails/rainbow-sparkle/app/views/flavors/edit.html.erb
<h1>Editing Flavor</h1>

<%= render 'form', flavor: @flavor %>

<%= link_to 'Show', @flavor %> |
<%= link_to 'Back', flavors_path %>

dev/307/rails/rainbow-sparkle/app/views/flavors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flavors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flavors.each do |flavor| %>
      <tr>
        <td><%= flavor.name %></td>
        <td><%= flavor.color %></td>
        <td><%= link_to 'Show', flavor %></td>
        <td><%= link_to 'Edit', edit_flavor_path(flavor) %></td>
        <td><%= link_to 'Destroy', flavor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flavor', new_flavor_path %>

dev/307/rails/rainbow-sparkle/app/views/flavors/new.html.erb
<h1>New Flavor</h1>

<%= render 'form', flavor: @flavor %>

<%= link_to 'Back', flavors_path %>

dev/307/rails/rainbow-sparkle/app/views/flavors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flavor.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @flavor.color %>
</p>

<%= link_to 'Edit', edit_flavor_path(@flavor) %> |
<%= link_to 'Back', flavors_path %>

dev/307/rails/rainbow-sparkle/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RainbowSparkle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>